# Generated by Django 5.1.2 on 2024-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_rename_usuario_perfil_user_remove_perfil_rol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='location',
        ),
        migrations.AddField(
            model_name='perfil',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
