# Generated by Django 5.1.2 on 2024-12-09 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0005_reserva_archivo_reserva_reserva_comentario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campo',
            name='deporte',
            field=models.CharField(default='futbol', max_length=50),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['-fecha_hora_inicio'], name='Aplicacion1_fecha_h_87be05_idx'),
        ),
    ]
