# Generated by Django 5.1.2 on 2024-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0006_alter_reserva_unique_together_campo_deporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
